name: Deploy to Staging
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@167.99.252.151 << 'EOF'
            cd /var/www/anton/anton-api
            git pull origin develop
            docker-compose down
            docker-compose up --build -d
          EOF
